### ISSUE TITLE
support output time format for NicoKaraMaker2

### ISSUE THREAD

**Issue by hundun000** [Juna-Idler/RhythmiKaRuTTE#9]
Current output time format `[00:00.00]` works in NicoKaraMaker1, but doesn't works in NicoKaraMaker2. The format that NicoKaraMaker2 used is `[00:00:00]` . 

Maybe be add a output time format switch?

**Comment by Juna-Idler** [comment]
[00:00:00] is an old format unique to Japan http://hp.vector.co.jp/authors/VA023256/TimeTagDev.html
Therefore, there is almost no merit to be able to output it.
Wouldn't it be better to ask "NicoKaraMaker2" to support [00:00.00]?

Alternatively, replace using a regular expression on a suitable text editor.

>[00:00:00]は日本独自の古い形式 http://hp.vector.co.jp/authors/VA023256/TimeTagDev.html
なので、それを出力できるようにするメリットはほとんどないからなあ。
「NicoKaraMaker2」に[00:00.00]の対応をお願いしたほうがいいんじゃないかな？
>
>もしくは適当なテキストエディタ上で正規表現を用いて置換する。

**Comment by hundun000** [comment]
It seems that though http://hp.vector.co.jp/authors/VA023256/TimeTagDev.html is old but still in use. Karaoke tool is less amount and the format standard not change for a long time. The newest [RhythmicaLyrics manual > 機能解説 > 保存形式](http://suwa.pupu.jp/Howto/RhythmicaLyrics/manual/doc/howto/stepHelp.html) show it uses [00:00:00] too.

**Comment by Juna-Idler** [comment]
http://suwa.pupu.jp/Howto/RhythmicaLyrics/manual/doc/other/history.html
> 2006年  5月24日 | Ver. 1.0 | ・完成

It's old software from 17 years ago, so yeah


> 17年前の古いソフトだから、そりゃそうよ

**Comment by Juna-Idler** [comment]
In the first place, NicoKaraMaker is not very compatible because the ruby specifications are different,
I see, if it's not Japanese, ruby doesn't matter.

I saw the specification on Wikipedia
https://en.wikipedia.org/wiki/LRC_(file_format)
https://ja.wikipedia.org/wiki/LRC_(%E3%83%95%E3%82%A1%E3%82%A4%E3%83%AB%E3%83%95%E3%82%A9%E3%83%BC%E3%83%9E%E3%83%83%E3%83%88)


> そもそもNicoKaraMakerとはルビの仕様が違うからあんまり相容れないんだが、
そうか、日本語じゃないならルビ関係ないのか。

>仕様書はWikipediaで見た

**Comment by hundun000** [comment]
>  NicoKaraMaker is not very compatible

OK. I find the way to run RhythmicaLyrics successfully. I will ues it for NicoKaraMaker.
